var trainData = [
[ "You are excited, you are so calm and relaxed, I miss you too", "positive"],
[ "We are talking today", "positive"],
[ "Fantastic", "positive"],
[ "Your flower ability", "positive"],
[ "Good publication radio", "positive"],
[ "No matter what happens, keep laughing", "positive"],
[ "Brothers if you are not so handsome and talented", "positive"],
[ "First part of the new year", "positive"],
[ "I am a footballer but it can be played at the time you play soccer", "positive"],
[ "Super great", "positive"],
[ "You are my father's car.", "positive"],
[ "I am a weary traveler my beautiful black", "positive"],
[ "I am very happy to thank you", "positive"],
[ "I am a friend of mine, I have been working with my friend for 8 years, I love you baby!", "positive"],
[ "Iste sessions: htt ...", "positive"], 
[ "if you do not have a fun section, are you still watching?","positive"],
[ "A beautiful man was born today is good", "positive"],
[ "Manga legend you made me clip girl", "positive"],
[ "I came in insallah: d was great", "positive"],
[ "How about watching for the first time in the Istiklal Caddesi and the pleasing camera rearviews ...", "positive"],
[ "Thank you", "positive"],
[ "Thank you", "positive"],
[ "Thank you for being one of the most entertaining films I have seen in the last year, thank you", "positive"],
[ "What's in the body and where it takes place in the mainstream, insallah awaits you in theaters", "positive"],
[ "Estafurullah I am very thankful to you that my soul is beautiful", "positive"],
[ "There is a miracle that man can only live once in his life", "positive"],
[ "I", "positive"], 
[ "when I left the film and started singing when I saw the microphone","positive"],
[ "Let's have our third day of fairytale", "positive"],
[ "A great day to go to the movies of happy markets Iste sessions:", "positive"],
[ "I am very grateful to you, my brother, what a beautiful man you are.", "positive"],
[ "Can Pucca be happy with molasses", "positive"],
[ "The most beautiful thing to do on Saturday is watching the mother-in-law", "positive"],
[ "I am very excited to watch my session at the end of the session", "positive"],
[ "I am sorry for the askin", "positive"],
[ "I am sure my friend, murat boz, has acted in the film today, I am confident that the film will be successful", "positive"],
[ "And there is no calm", "positive"],
[ "I have waited for the present for months now.","positive"],
[ "Everyone who is not a sad movie is not satisfied with watching movies", " positive "],
[ "Let's hopefully have a good movie today in the sight of the audience", "positive"],
[ "Look, baby, come on we are in the vision today, we are as passionate and excited as you guys are,", "positive"],
[ "We do not know anymore", "positive"],
[ "After the pride of being in the same staff with them, we have seen happiness and honor ...", "positive"],
[ "You can watch your hands on the screens often in half a day", "positive"],
[ "I am lonely if this is supposed to be glad to us", "positive"],
[ "It is great pleasure to hear it from you", "positive"],
[ "Thank you very sincerely,", "positive"],
[ "I am delighted to be working with maximum care and sensitivity", "positive"],
[ "We have caught pastic hotpots", "positive"],
[ "Someone rich in copyright in our country has not yet seen, but what we value most is our love", "positive"],
[ "I'm calling Erdogan, I do not have phones, Hahhaa", "positive"],
[ "These guys are doing nice things", "positive"],
[ "Beautiful magazine", "positive"],
[ "Happy holidays", "positive"],
[ "I am very grateful that you have been very happy, I love you", "positive"],
[ "Where do these guys look", "positive"],
[ "Demon", "positive"],
[ "Haha alemsin önder ya", "positive"],
[ "Both man and 3 man", "positive"],
[ "Again hi and greeted oguzhan", "positive"],
[ "Come on", "positive"],
[ "That's the beauty of your heart", "positive"],
[ "For", "positive"],
[ "We have done the biggest digital feminine choir of turkey that we do:", "positive"],
[ "From the festival center show", "positive"],
[ "What do you do as you do kz", "positive"],
[ "Good", "positive"],
[ "I am alive now in my program", "positive"],
[ "Tomorrow, at 10 o'clock in CNNTurk, I will sing a live broadcast on the program of Hakan Celik", "positive"],
[ "Thank you for everybody who is covered in the cover, and everyone else is happy", "positive"],
[ "I do not believe in the chocolate that comes home"," positive "],
[ "It was very happy to take part in that wonderful movie sarki all that was played that night", "positive"],
[ "Thank you", "positive"],
[ "Wake up a good news", "positive"],
[ "I greet you with affection for meeting good news, take good care of yourself.", "positive"],
[ "Sometimes it is not necessary to spend the night, but it is an unnecessary vigorousness.", "negative"],
[ "Our country is so much to do with the sad people, the instagram is ambush to comment ...", "negative"],
[ "March 21st world-wide-day syndrome is not a disease of genetic ...", "negative"],
[ "We have kept this sunshine we are not kept", "negative"],
[ "I do not think it's up to date, but I do not find the answer to this question,", "negative"],
[ "Australia academy awards best assistant male actor this death is not such a success darisi oskar congratulations Master", "negative"],
[ "Tonight at 00:00 here too, We are in a bit of a late night, yes, but not power", "negative"],
[ "This is not the head, even the house you find difficult, we civilized people we", "negative"],
[ "We are going to enter the new plane in the air, but the team has made a 13:14 flight, so we are still in the ...", "negative"],
[ "Exactly", "negative"],
[ "Moralim ok bad", "negative"],
[ "I want to cry", "negative"],
[ "I am so glad that the juniors of junior high schools are not keen on getting out of the album, but I am so curious and excited ...", "negative"],
[ "I do not have a lot of dribbling at home, but I have no dreams", "negative"],
[ "If you know the serenade's father, greetings or aggravation", "negative"],
[ "The rosy ergen is terrible, the oguzhan coach - it's not me that I'm not asking you to step back", "negative"],
[ "Not bad", "negative"],
[ "I can not listen at all these days", "negative"],
[ "I apologize", "negative"],
[ "Disgrace", "negative"],
[ "What to do", "negative"],
[ "Moralim is very bad", "negative"],
[ "I can not fall asleep", "negative"],
[ "I want to cry", "negative"],
[ "Came around", "negative"],
[ "How bad a human being", "negative"],
[ "I am very disgusted", "negative"],
[ "Where is this country going", "negative"],
[ "The new Whatsapp interface is not very nice", "negative"],
[ "We lost more of a master player who grew up with films", "Let's go to the basement, make the place a paradise Zeki Alasy", "negative"],
[ "The human being who does not know the face, the person who does not know is the one who protects from him", "negative"],
[ "Alla is out of nowhere and I do not even think about who the mortar is","negative"],
[ "In the end a mediocre movie makes me think that this is because of the expectation", "negative"],
[ "Bad and time-consuming, I am not at all pissed off and I have very unnecessary bloody scenes", "negative"],
[ "My mind is getting me something nervous, I think I'm crazy these cars, home, enough hours", "negative"],
[ "Zumrecilik is a complete poison ignorant drug cunning go to sopasis soon", "negative"],
[ "You smell so bad", "negative"],
[ "Our democracy is mediocre, there are problems about rights and freedoms, the state of law is legal, economic growth has stopped, we have no right to share.", "negative"],
[ "The situation to take over is not mercedes mercedes, this miner is the words of our brother", "negative"],
[ "Your persecution will continue to increase, your reign will be faster.", "negative"],
[ "Not to know, not to swear", "negative"],
[ "This is enough for the day of Sali, Bitsin no longer", "negative"],
[ "You blew the blood, squirt your kit .. Enough is enough", "negative"],
[ "Is it me,", "negative"], 
[ "If I get caught in the voice", "negative"],
[ "Emre Belözoglu'a attacking friends I am a human being, we are also coming!", "negative"],
[ "I went to the tribe like girls who have not been lovers for many years, I gotta love it when I see someone hand in hand on the way", "negative"],
[ "It's a big year I've just finished this year like it's every year, I think it's the wrong one, it's not my fault I'm born sane", "negative"],
[ "Bash agriyor", "negative"],
[ "Do not see what is blooming", "negative"],
[ "I'm tired of leaving everything to time, going to beat someone, spit on someone's face", "negative"],
[ "Be a human being a little human, but be a full human being in this phrase!", "negative"],
[ "You can swim or kill a woman in the middle of the street, but the populist society reacts because it is a society with values.", "negative"],
[ "Today we have pidelers tardy", "negative"],
[ "Unfortunately, these triplets do not work on me", "negative"],
[ "Even if I have a very confused fortune-telling feeling, I still do not have that direction in all my life", "negative"],
[ "I live the same tension every summer when it comes to Istanbul, it looks very inward, it is invisible, it is open to the naked.","negative"],
[ "In this life I saw how hated the man I once used to call his brother", "negative"],
[ "My beliefs are over, look at the pain,", "negative"],
[ "Mommy has just been sad for the last time this year. I'm having emotional moments", "negative"],
[ "Nobody wants to be interested in me, I want to love you, but when you go away from me, moralim breaks down. The child at 5 is more intelligent than me,", "negative"],
[ "I am even more nervous when I am already nervous. I have been sleeping for a few years", "negative"],
[ "What a shitty day", "negative"],
[ "I hate everybody at certain intervals, we can call the hani two or three times a month.", "negative"],
[ "Knowing all the evil events against the spell or magic is present, because there is evil", "negative"],
[ "Morales corrupt voice", "negative"],
[ "Or poison does not flow out as long as the poison does not flow out", "negative"],
[ "I just cried that the weather was too hot", "negative"],
[ "It can not be such a stinking sock", "negative"],
[ "Life is hard", "negative"],
[ "Everyone is dead, some are earth, some are buried in hearts", "negative"],
[ "Sucker who came to Istanbul without going to the sea because he was sick but saliva slippery patient", "negative"],
]

module.exports = trainData;